sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.10.3
before_install:
  - sudo apt-get update -yq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -yq docker-ce
install:
  - go get -u github.com/vbatts/git-validation
script:
  - git-validation -run DCO,short-subject
  - go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
  - go vet $(go list ./... | grep -v vendor)
  - go test $(go list ./... | grep -v vendor)

